<head>
<?php
include 'connect.php';
?>
<head>
<style type="text/css">
		    ul {
font-family: Arial, Verdana;
font-size: 16px;
margin: 0;
padding: 0;
list-style: none;
}
ul li {
display: block;
position: relative;
float: left;
}
li ul {
display: none;
}
ul li a {
display: block;
text-decoration: none;
color: #ffffff;
border-top: 1px solid #ffffff;
padding: 10px 20px 10px 20px;
background: #006699;
margin-left: 1px;
white-space: nowrap;
}
ul li a:hover {
background: #617F8A;
}
li:hover ul {
display: block;
position: absolute;
}
li:hover li {
float: none;
font-size: 11px;
}
li:hover a {
background: #617F8A;
}
li:hover li a:hover {
background: #95A9B1;
}/* CSS Document */

</style>
</head>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>report</title>

<link href="css/ui-lightness/jquery-ui-1.10.2.custom.css" rel="stylesheet">
	<script src="js/jquery-1.9.1.js"></script>
	<script src="js/jquery-ui-1.10.2.custom.js"></script>
<script>
$(function(){
$( "#accordion" ).accordion();
$( "#tabs" ).tabs();
})
</script>
</head>
<div style="background-color:#3399FF">
<table class="header" height="1%" width="100%">
<tr><td align="center"><img src="images/logo.jpg" height="95" /></td></tr>
</table>
</div>
<style type="text/css">
<!--
body{
		font: 82.5% "Trebuchet MS", sans-serif;
		margin: 30px;
	}

body{background-color:#FFFFFF}
.container{border:solid; border-color:#3399FF}
.menu1{background-color:#33CCFF; text-align:justify}
.footer{background-color:#3399FF}
.mini{background-color:#3366CC}
.header{background-color:#3399FF}
a{color:#FFFFFF; font-family:"Microsoft Sans Serif"}
-->
</style>
   <div class="container" align="center">
  <!--main part-->
  <div class="menu1" align="center">
<div class="nav" style="height:0.2%; width:100%; font-size:14px">
<ul id="drop">
      <li><a href="reports.php">Home</a></li>
      <li><a href="">staff</a>
        <ul>
        <li><a href="staffReg.php">Register new staff</a></li>
        </ul>
      </li>
	   <li><a href="change.php">Account</a></li>
      <li><a href="anews.php">help</a></li>
    </ul><br><br /><br />
	</div>
</div>
<?php
session_start();

if(!isset($_SESSION['username']))
{
header("location:index.php");
}
        
		echo "<p align=right>". $_SESSION['username']. "&nbsp;&nbsp;<a href=logout.php><font color=blue>logout</font></a></b></p>";
		
?>
<br />
<p align="right"><table>
<form action="admin.php" method="post">
<tr><td>staff:<input type="text" name="search" /></td>
<td><input type="submit" name="searchbutton" value="search" /></td></tr>
</form>
</table></p>
<strong><u>HOW TO USE THE SYSTEM AS SUPERVISOR</u></strong><br/>
All the functions that the system can perform are summerised within the menu above. So to navigate through the whole system, make use of the menu to go to whichever page you want to go to.<br/>
<br/>
<div id="accordion">

<h3 align="left">home</h3>
<div>This is the supervisor home page and it contains all reports that are generated by the system.</div>
<h3 align="left">register staff</h3>
<div>
This item helps you the supervisor to register new staff members who are allowed to use the system</div>

<h3 align="left">Account</h3>
<div>
This helps you to change your user account details</div>
<h3 align="left">help</h3>
<div>
This is the exact page where you are. It teaches you how to use the system</div>
</div>
<table class="footer" height="2%" width="100%">
<tr><td><h6 align="center">&copy;All rights reserved</h6></td></tr>
</table>